name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio run
    - uses: actions/upload-artifact@v2
      with:
        name: .pio/build/stm8sblue_debug/firmware.ihx
        path: debug_firmware.ihx
        if-no-files-found: error
    - uses: actions/upload-artifact@v2
      with:
        name: .pio/build/stm8sblue_debug/firmware.elf
        path: debug_firmware.elf
        if-no-files-found: error
    - uses: actions/upload-artifact@v2
      with:
        name: .pio/buildstm8sblue_release/firmware.ihx
        path: release_firmware.ihx
        if-no-files-found: error
    - uses: actions/upload-artifact@v2
      with:
        name: .pio/build/stm8sblue_release/firmware.elf
        path: release_firmware.elf
        if-no-files-found: error
